package it.unipv.ingsfw.view;

import java.util.ArrayList;

import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JList;
import javax.swing.JPanel;
import javax.swing.JPasswordField;
import javax.swing.JSpinner;
import javax.swing.JTextArea;
import javax.swing.JTextField;
import javax.swing.SpinnerNumberModel;
import javax.swing.border.Border;

public interface IRistoranteGUI {
	public void refreshPanel();
	public void startPage();
	public void lastClientPage();
	public JButton getStartButton();
	public void sceltaPersona();
	public void identificaClienteR();
	public void scegliMenuR();
	public void clienteNoPrenotatoR(int i);
	public void identificaDipendenteR();
	public JFrame getF();
	public void vediOrdiniR(String ordiniText);
	public void addDishR();
	public void aggiungiPrenotazioneR(int max);
	public void operazioniDipendenteR();
	public void inviaOrdineR(ArrayList<String> nomi, ArrayList<Integer> quantita);
	public void aggiungiPannello(JPanel panel);
	public void popUpErrore(String s);
	public JButton getTornaIndietroButton();
	public JLabel getLab();
	public void setLab(String s);
	public JPanel getP();
	public JPanel getP2();
	public JLabel getLabIdentificazione();
	public JButton getStart();
	public JButton getClienteButton();
	public JButton getDipendenteButton();
	public Border getBordo();
	public int getHeight();
	public int getWidth();
	public JPasswordField getPasswordRistorante();
	public char[] getPasswordOfPasswordRistorante();
	public JButton getAggiungiPrenotazioneButton();
	public JButton getAggiungiQuantitaButton();
	public JButton getVediOrdiniButton();
	public JButton aggiungiPrenotazioneButton();
	public JTextField getClienteDaPrenotare();
	public String getTextOfClienteDaPrenotare();
	public JSpinner getClienteNoPrenotatoD();
	public int getValueOfClienteNoPrenotatoD();
	public JButton getPrenotaClienteButton();
	public JTextField getNomeClienteField();
	public String getTextNomeClienteField();
	public JButton getNoPrenotazioneButton();
	public JButton getSceltaMenuButton();
	public JSpinner getClienteNoPrenotato();
	public int getValueClienteNoPrenotato();
	public JButton getAyceButton();
	public JButton getALaCaButton();
	public JList getPiattiMenu();
	public int getSelectedIndexOfPiattiMenu();
	public Object getSelectedValueOfPiattiMenu();
	public JSpinner getQuantPiattoSpinner();
	public int getValueOfQuantPiattoSpinner();
	public SpinnerNumberModel getValueC();
	public int getMinimumOfValueC();
	public int getValueOfValueC();
	public void setValueOfValueC(int i);
	public void setMaxOfValueC(int i);
	public void azzeraValueC();
	public SpinnerNumberModel getValueD();
	public void setMaxOfValueD(int i);
	public void setValueOfValueD(int i);
	public int getValueOfValueD();
	public JLabel getTotale();
	public void setTextOfTotale(String s);
	public JButton getinviaOrdineButton();
	public JButton getAggiungi();
	public JTextField getNomePiattoField();
	public String getTextOfNomePiattoField();
	public JSpinner getQuantitySpinner();
	public int getValueOfQuantitySpinner();
	public JTextArea getOrdini();
	public void setTextOfOrdini(String s);
	public JButton getPreparaTuttoButton();
	public JButton getChiediContoButton();
	public void setTextOfNomeClienteField(String s);
	public void setTextOfClienteDaPrenotare(String s);
	public void setTextOfNomePiattoField(String s);
	public JButton getHomeButton();
	public JButton getHomeClienteButton();
	public JLabel getPostiLiberiLabel();
	public JLabel getClientiPrenotatiLabel();
	public JButton getVediPrenotazioniButton();
	public JTextArea getPrenotazioniArea();
	public void setTextOfPostiLiberiLabel(String s);
	public void setTextOfClientiPrenotatiLabel(String s);
	public String getDefaultTextOfLabPosti();
	public String getDefaultTextOfLabClientiPrenotati();
	public String getDefaultTextOfTotale();
}
